services:
  redis: 
    container_name: grid_redis
    image: redis:7.4.2
    env_file:
      - .env
    networks:
      - internal
    ports:
      - ${REDIS_PORT}:6379
    restart: always
    volumes: 
      - ./volumes/redis-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  mariadb:
    container_name: grid_mariadb
    image: mariadb:10.6
    env_file:
      - .env
    networks:
      - internal
    ports:
      - ${MARIADB_PORT}:3306
    restart: always
    volumes:
      - ./volumes/mariadb-data:/var/lib/mysql
      - ./volumes/mariadb-logs:/var/log/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  backend:
    container_name: grid_backend
    build: 
      context: ./docker
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    command: /scripts/backend.dev.sh
    privileged: true
    networks:
      - internal
    depends_on:
      - mariadb
      - redis 
    ports:
      - ${BACKEND_PORT}:4000
    restart: always
    volumes:
      - ./backend:/app
      - ./scripts:/scripts
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  frontend:
    container_name: grid_frontend
    build: 
      context: ./docker
      dockerfile: Dockerfile.frontend
    user: node
    env_file:
      - .env
    command: /scripts/frontend.dev.sh
    privileged: true
    depends_on:
      - backend
    networks:
      - internal
    ports:
      - ${FRONTEND_PORT}:5173
    volumes:
      - ./frontend:/app
      - ./scripts:/scripts
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

networks:
  internal:
