services:
  redis: 
    container_name: grid_redis
    image: redis:7.4.2
    env_file:
      - .env
    networks:
      - internal
    ports:
      - ${REDIS_PORT}:6379
    restart: always

  mariadb:
    container_name: grid_mariadb
    image: mariadb:10.6
    env_file:
      - .env
    networks:
      - internal
    ports:
      - ${MARIADB_PORT}:3306
    restart: always
    volumes:
      - ./volumes/mariadb-data:/var/lib/mysql
      - ./volumes/mariadb-logs:/var/log/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  backend:
    container_name: grid_backend
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.backend.prod
    env_file:
      - .env
    command: /scripts/backend.prod.sh
    privileged: true
    networks:
      - internal
    depends_on:
      - mariadb
      - redis 
    ports:
      - ${BACKEND_PORT}:4000
    restart: always
    volumes:
      - ./volumes/logs-backend/:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  frontend:
    container_name: grid_frontend
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.frontend.prod
    user: node
    env_file:
      - .env
    command: /scripts/frontend.prod.sh
    depends_on:
      - backend
    networks:
      - internal
    ports:
      - ${FRONTEND_PORT}:5173
    volumes:
      - ./volumes/logs-frontend/:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

networks:
  internal:
