FROM node:20 AS build

WORKDIR /app

RUN apt update && apt upgrade -y

COPY /backend /app
COPY /backend/ecosystem.config.js /app/ecosystem.config.js
COPY /scripts /scripts

RUN yarn install
RUN yarn build



FROM node:20

WORKDIR /app
COPY --from=build /app/dist /app/dist
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/ecosystem.config.js /app/ecosystem.config.js
COPY --from=build /scripts /scripts

RUN apt update && apt upgrade -y
RUN npm install pm2 -g
