FROM node:20 AS build

WORKDIR /app

COPY /backend /app

RUN apt update && apt upgrade -y
RUN yarn build



FROM node:20

WORKDIR /app
COPY --from=build /app/dist /app/dist
COPY /backend/node_modules /app/node_modules
COPY /backend/ecosystem.config.js /app/ecosystem.config.js
COPY /scripts /scripts

RUN apt update && apt upgrade -y
RUN npm install pm2 -g
