FROM node:20 AS build

WORKDIR /app

COPY /frontend /app
COPY /scripts /scripts

RUN yarn install
RUN yarn build


FROM node:20 

WORKDIR /app

COPY --from=build /app/dist /app/dist
COPY --from=build /app/ecosystem.config.js /app/ecosystem.config.js
COPY --from=build /scripts /scripts

RUN npm install pm2 serve -g -y
